/**
 * 全站统一中文文案字典
 * 所有前端页面和后端通知中的文本必须通过此文件引用
 * 按模块分组，严禁在组件中硬编码中文文本
 */

export const COPY = {
  // ============================================================
  // 品牌 & 通用
  // ============================================================
  BRAND: {
    NAME: "SnapGown",
    TAGLINE: "预约你的毕业照拍摄",
    DESCRIPTION: "在杜伦大学找到专业摄影师。选择时间段，通过微信支付，获得精美的毕业照。",
  },

  COMMON: {
    LOGIN: "登录",
    GET_STARTED: "立即注册",
    DASHBOARD: "控制台",
    ADMIN: "管理后台",
    LOGOUT: "退出登录",
    LOADING: "加载中...",
    NO_DATA: "暂无数据",
    CONFIRM: "确认",
    CANCEL: "取消",
    SUBMIT: "提交",
    SAVE: "保存",
    DELETE: "删除",
    EDIT: "编辑",
    SEARCH: "搜索...",
    BACK: "返回",
    VIEW_ALL: "查看全部",
    VIEW_DETAILS: "查看详情",
    ACTIONS: "操作",
    STATUS: "状态",
    AMOUNT: "金额",
    DATE: "日期",
    TIME: "时间",
    NAME: "姓名",
    PHONE: "电话",
    WECHAT: "微信",
    PHOTOGRAPHER: "摄影师",
    STUDENT: "学生",
  },

  // ============================================================
  // 首页
  // ============================================================
  HOME: {
    HERO_TITLE: "预约你的毕业照拍摄",
    HERO_SUBTITLE: "在杜伦大学找到专业摄影师。选择时间段，通过微信支付，获得精美的毕业照。",
    LOCATION: "杜伦大学",
    INSTANT_BOOKING: "即时预约",
    WECHAT_PAYMENT: "微信支付",
    AVAILABLE_PHOTOGRAPHERS: "可用摄影师",
    NO_PHOTOGRAPHERS: "暂无可用摄影师，请稍后再来！",
    VIEW_SLOTS_BOOK: "查看档期 & 预约",
    WELCOME_BACK: "欢迎回来，{name}！",
    PHOTOGRAPHER_SUBTITLE: "管理你的预约和可用档期，开始接受毕业照拍摄请求。",
    ACTIVE_SLOTS: "个可用档期",
    PENDING_ORDERS: "个待处理订单",
    MANAGE_ORDERS: "管理订单",
    MANAGE_ORDERS_DESC: "查看和管理来自学生的预约请求。",
    MANAGE_AVAILABILITY: "管理可用档期",
    MANAGE_AVAILABILITY_DESC: "设置你的可用时间段供学生预约。",
    ADMIN_DASHBOARD: "管理员控制台",
    ADMIN_SUBTITLE: "管理摄影师、订单和平台设置。",
    PHOTOGRAPHERS: "摄影师",
    PHOTOGRAPHERS_DESC: "审核和批准摄影师申请。",
    MANAGE_PHOTOGRAPHERS: "管理摄影师",
    ORDERS: "订单",
    ORDERS_DESC: "查看和管理平台上的所有订单。",
    VIEW_ORDERS: "查看订单",
    ADMIN_PANEL: "管理面板",
    ADMIN_PANEL_DESC: "访问完整的管理后台和数据分析。",
    OPEN_ADMIN_PANEL: "打开管理面板",
  },

  // ============================================================
  // 支付 & 结算
  // ============================================================
  CHECKOUT: {
    PAYMENT_TITLE: "支付",
    WECHAT_PAY_INSTRUCTION: (rmb: string, gbp: string) =>
      `请扫描下方微信二维码支付共计 ¥${rmb} 元（折合 £${gbp}）`,
    REF_CODE_WARNING: "【极重要警告】请务必在微信转账的【添加备注/说明】中填写此参考码：",
    REF_CODE_CONSEQUENCE: "否则摄影师将无法为您确认档期！",
    PAYMENT_WINDOW: "30分钟支付窗口",
    PAYMENT_WINDOW_DESC: (rmb: string) =>
      `请在 30 分钟内通过微信向摄影师转账 ¥${rmb}，然后上传付款截图。`,
    UPLOAD_PROOF: "上传付款凭证",
    PROOF_SUBMITTED: "付款凭证已提交",
    PROOF_SUBMITTED_DESC: "摄影师有 12 小时来确认你的付款。确认后你会收到通知。",
    BOOKING_CONFIRMED: "预约已确认！",
    BOOKING_CONFIRMED_DESC: (date: string) => `你的毕业照拍摄已确认。${date} 见！`,
    PAY_NOW: "立即支付",
    ORDER_NUMBER: "订单号",
    PAYMENT_REF: "支付参考码",
    PHOTOGRAPHER_LABEL: "摄影师",
    TOTAL: "总计",
  },

  // ============================================================
  // 学生控制台
  // ============================================================
  STUDENT: {
    MY_BOOKINGS: "我的预约",
    BOOKING_HISTORY: "预约历史",
    NO_BOOKINGS: "暂无预约。",
    BROWSE_PHOTOGRAPHERS: "浏览摄影师",
    PROOF_SUBMITTED_NOTICE: "您的付款凭证已成功提交。当前档期已为您安全锁定。摄影师正为您核对账单中（最长不超过12小时）。若超时未处理，平台官方客服将直接介入协助，请您放心。",
    VIEW_BOOKINGS: "查看预约",
    LOGIN_TO_VIEW: "请登录查看你的预约。",
    ORDER_NO: "订单号",
    PAYMENT_REF: "支付参考码",
    PHOTOGRAPHER: "摄影师",
    DATE: "日期",
    TIME: "时间",
    AMOUNT: "金额",
    STATUS: "状态",
    ACTION: "操作",
  },

  // ============================================================
  // 摄影师控制台
  // ============================================================
  PHOTOGRAPHER_DASHBOARD: {
    TITLE: "摄影师控制台",
    MANAGE_SLOTS: "管理档期",
    ORDER_MANAGEMENT: "订单管理",
    NO_ORDERS: "暂无订单。创建可用档期开始接收预约！",
    CONFIRM_PAYMENT: "确认",
    REJECT_PAYMENT: "拒绝",
    MARK_COMPLETE: "标记完成",
    VIEW_PROOF: "查看凭证",
    ORDER: "订单",
    PAYMENT_REF: "支付参考码",
    STUDENT: "学生",
    DATE: "日期",
    AMOUNT: "金额",
    STATUS: "状态",
    PROOF: "凭证",
    ACTIONS: "操作",
    DEBT_WARNING: "欠款警告",
    ACCOUNT_SUSPENDED: "账户已暂停",
    OUTSTANDING_COMMISSION: "待付佣金",
    SUSPENDED_MESSAGE: "你的账户已被暂停。请联系管理员结算佣金。",
    COMMISSION_MESSAGE: "请与平台结算佣金。",
    LOGIN_TO_VIEW: "请登录查看你的订单。",
    REJECT_DIALOG_TITLE: "拒绝付款",
    REJECT_DIALOG_DESC: "请提供拒绝付款凭证的原因。",
    REJECT_REASON_PLACEHOLDER: "拒绝原因...",
    REJECT_AND_RELEASE: "拒绝并释放",
  },

  // ============================================================
  // 管理员控制台
  // ============================================================
  ADMIN: {
    OVERVIEW: "概览",
    ORDERS: "订单",
    PHOTOGRAPHERS: "摄影师",
    COMMISSION: "佣金",
    STUDENTS: "学生",
    PLATFORM_OVERVIEW: "平台概览",
    FAILED_TO_LOAD: "加载管理员数据失败。请确认你以管理员身份登录。",
    PENDING_PAYMENT: "待支付",
    AWAITING_VERIFICATION: "待审核",
    CONFIRMED: "已确认",
    OVERDUE: "已超期",
    COMPLETED: "已完成",
    CANCELLED: "已取消",
    COMMISSION_OWED: "待付佣金",
    PENDING_APPROVALS: "待审核",
    TOTAL_STUDENTS: "总学生数",
    TOTAL_PHOTOGRAPHERS: "总摄影师数",
    RECENT_ORDERS: "最近订单",
    PENDING_PHOTOGRAPHERS: "待审核摄影师",
    NO_ORDERS_YET: "暂无订单。",
    NO_PENDING_APPROVALS: "暂无待审核申请。",
    REVIEW: "审核",
    REVIEW_NOW: "立即审核",
    PENDING_APPROVAL: "待审核",
    NO_PHOTOGRAPHERS_PENDING: "暂无待审核的摄影师。",
    ALL_PHOTOGRAPHERS: "所有摄影师",
    NO_PHOTOGRAPHERS_REGISTERED: "暂无注册摄影师。",
    NO_PHOTOGRAPHERS_MATCH: "没有匹配搜索的摄影师。",
    APPROVE: "批准",
    REJECT: "拒绝",
    SUSPEND: "暂停",
    UNSUSPEND: "恢复",
    CLEAR_DEBT: "清除欠款",
    APPROVAL: "审核状态",
    ACCOUNT: "账户状态",
    DEBT: "欠款",
    SUSPEND_DIALOG_TITLE: "暂停摄影师？",
    SUSPEND_DIALOG_DESC: "这将阻止摄影师接收新的预约。",
    UNSUSPEND_DIALOG_TITLE: "恢复摄影师？",
    UNSUSPEND_DIALOG_DESC: "这将恢复摄影师接收预约的能力。",
    CLEAR_DEBT_DIALOG_TITLE: "清除欠款？",
    CLEAR_DEBT_DIALOG_DESC: "这将把摄影师的佣金欠款设为 £0.00 并恢复其账户。",
    PHOTOGRAPHER_APPROVED: "摄影师已批准",
    PHOTOGRAPHER_REJECTED: "摄影师已拒绝",
    ACCOUNT_SUSPENDED: "账户已暂停",
    ACCOUNT_REACTIVATED: "账户已恢复",
    DEBT_CLEARED: "欠款已清除，账户已恢复",
    SEARCH_PHOTOGRAPHERS: "按姓名或微信搜索...",
    SEARCH_ORDERS: "按订单号、支付参考码、学生或摄影师搜索...",
    FILTER_BY_STATUS: "按状态筛选",
    ALL_STATUSES: "所有状态",
    URGENT_ORDERS: "紧急订单（需要处理）",
    ALL_ORDERS: "所有订单",
    REJECT_ORDER: "拒绝订单",
    REJECT_ORDER_DESC: "这将取消订单并释放档期。请提供原因。",
    REJECT_REASON_PLACEHOLDER: "拒绝原因...",
    REJECT_AND_RELEASE: "拒绝并释放",
    ORDER_CONFIRMED: "订单已由管理员确认",
    ORDER_REJECTED: "订单已拒绝，档期已释放",
    PAYMENT_PROOF: "付款凭证",
    // 佣金
    COMMISSION_LEDGER: "佣金账本",
    PENDING: "待处理",
    SETTLED: "已结算",
    WAIVED: "已免除",
    TOTAL_ENTRIES: "总条目数",
    SEARCH_COMMISSION: "按摄影师或订单号搜索...",
    NO_ENTRIES_MATCH: "没有匹配筛选的条目。",
    NO_ENTRIES_YET: "暂无佣金条目。",
    ORDER_AMOUNT: "订单金额",
    COMMISSION_AMOUNT: "佣金",
    SETTLE: "结算",
    WAIVE: "免除",
    SETTLED_ON: "结算于",
    SETTLE_DIALOG_TITLE: "标记为已结算？",
    SETTLE_DIALOG_DESC: "这将标记佣金为已支付。此操作应在确认收款后进行。",
    WAIVE_DIALOG_TITLE: "免除佣金？",
    WAIVE_DIALOG_DESC: "这将免除此佣金并减少摄影师的欠款。确定吗？",
    COMMISSION_SETTLED: "佣金已标记为已结算",
    COMMISSION_WAIVED: "佣金已免除",
    // 学生
    STUDENTS_TITLE: "学生",
    SEARCH_STUDENTS: "按姓名、微信或电话搜索...",
    NO_STUDENTS_MATCH: "没有匹配搜索的学生。",
    NO_STUDENTS_REGISTERED: "暂无注册学生。",
    ORDERS_COUNT: "订单数",
    TOTAL_SPENT: "总消费",
    LAST_ACTIVE: "最后活跃",
    TOTAL_REVENUE: "总收入",
  },

  // ============================================================
  // 摄影师公共页面
  // ============================================================
  PHOTOGRAPHER_PAGE: {
    AVAILABLE_SLOTS: "可用时间段",
    RESERVING: "正在为你保留档期...",
    VIEW_SLOTS: "查看档期 & 预约",
    BOOK_NOW: "立即预约",
    CONTACT_WECHAT: "微信联系",
  },

  // ============================================================
  // 认证
  // ============================================================
  AUTH: {
    LOGIN_TITLE: "登录",
    REGISTER_TITLE: "注册",
    EMAIL: "邮箱",
    PASSWORD: "密码",
    CONFIRM_PASSWORD: "确认密码",
    FORGOT_PASSWORD: "忘记密码？",
    RESET_PASSWORD: "重置密码",
    SEND_RESET_LINK: "发送重置链接",
    CHECK_EMAIL: "查看邮箱",
    CHECK_EMAIL_DESC: "我们已向 {email} 发送了验证链接。",
    NEXT_STEPS: "后续步骤：",
    STEP_1: "打开你的邮箱",
    STEP_2: "点击验证链接",
    STEP_3: "返回此处登录",
    EMAIL_SENT: "邮件已发送",
    EMAIL_SENT_DESC: "如果存在 {email} 的账户，你将很快收到密码重置链接。",
    PASSWORD_UPDATED: "密码已更新",
    PASSWORD_UPDATED_DESC: "你的密码已成功更改。",
    REDIRECTING: "将在 {countdown} 秒后跳转到登录...",
    GO_TO_LOGIN: "立即跳转登录",
    PASSWORD_STRENGTH: {
      WEAK: "弱",
      FAIR: "一般",
      GOOD: "良好",
      STRONG: "强",
    },
    ROLE_STUDENT: "学生",
    ROLE_PHOTOGRAPHER: "摄影师",
    STEP_1_TITLE: "选择角色",
    STEP_2_TITLE: "完善信息",
    CUSTOM_PROFILE_URL: "自定义主页链接",
    CUSTOM_PROFILE_URL_HINT: "例如 alvin，你的主页将是 /photographers/alvin",
    ALREADY_REGISTERED: "此邮箱已注册。请直接登录。",
    REGISTRATION_SUCCESS: "注册成功！",
    REGISTRATION_SUCCESS_DESC: "请查看邮箱完成验证。",
    RESEND_EMAIL: "重发邮件",
  },

  // ============================================================
  // 邮件模板
  // ============================================================
  EMAIL: {
    PAYMENT_NOTIFICATION_TITLE: "新的付款凭证待审核",
    PAYMENT_NOTIFICATION_BODY: "学生已上传付款凭证，请及时审核。",
    OVERDUE_ALERT_TITLE: "订单审核超时提醒",
    OVERDUE_ALERT_BODY: "以下订单已超过 12 小时未审核，请及时处理。",
    SUSPENSION_NOTICE_TITLE: "账户暂停通知",
    SUSPENSION_NOTICE_BODY: "由于佣金欠款超过阈值，你的账户已被暂停。",
    VIEW_ORDER: "查看订单",
    CONTACT_SUPPORT: "联系客服",
  },
} as const;

export default COPY;
